In [3]:
%pwd

'c:\\Users\\TransOrg\\Desktop\\demo-docker\\notebooks'

In [4]:
import os
os.chdir("..")

In [7]:
import pandas as pd
df = pd.read_csv("data/DataScience_Salaries.csv")
df.sample(3)

,work_year,job_title,job_category,salary,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
231,2025.0,Adversarial ML Engineer,Adversarial ML,178000.0,United States,Mid,Full-time,In-person,"Boston, MA",Large
1,2025.0,Machine Learning Engineer,Machine Learning,175000.0,United States,Mid,Full-time,Hybrid,"New York, NY",Large
764,2025.0,Universal Divine Truth Matrix Specialist,Divine Truth Computing,535000.0,United States,Senior,Full-time,In-person,Truth Universal,Infinite

In [10]:
from pycaret.regression import *
target = "salary"

reg = setup(
    data=df,
    target=target,
    session_id=42,
    train_size=0.75,
    normalize=True,
    transformation=True,
    remove_multicollinearity=True,
    multicollinearity_threshold=0.9,
    verbose=False
)

In [13]:
best_model = compare_models()
best_model

Initiated  . . . . . . . . . . . . . . . . . .              11:23:57
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

c:\Users\TransOrg\Desktop\demo-docker\venv\Lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:339: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(highlight_cols, subset=["TT (Sec)"])

HuberRegressor()

In [14]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [16]:
pred_holdout = predict_model(best_model)

In [19]:
new_data = df.copy().drop('salary',axis=1)
predictions = predict_model(best_model, data = new_data)

In [20]:
save_model(best_model,"best_pipeline")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['work_year'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['job_title', 'job_category',
                                              'employee_residence',
                                              'experience_level',
                                              'employment_type', 'work_setting',
                                              'company_location',
                                              'company_size'],
                                     transformer=SimpleImputer(s...
                                                                     'employee_residence',
                                                                     'company_location'],
                                                               handle_missing='return_nan'))),
                 ('remove_multicollinearity',
                  TransformerWrapper(exclude=[],
                                     transformer=RemoveMulticollinearity(threshold=0.9))),
                 ('transformation',
                  TransformerWrapper(transformer=PowerTransformer(standardize=False))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('trained_model', HuberRegressor())]),
 'best_pipeline.pkl')